version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Nothing to pre_build"
  build:
    commands:
      - cp src/environments/environment.local.ts src/environments/environment.ts
      - ng test --karmaConfig=src/karma.conf.aws.js --no-watch
  post_build:
    commands:
      - export now=$(date -u +'%S-%M-%H-%d-%m-%Y')
      - aws s3 sync tests/ $REPORT_PATH/report_$now
      - aws sns publish --topic-arn $NOTIFIER_TOPIC --message "practera-cutie unit tests completed for $CODEBUILD_SOURCE_VERSION, the test report is $REPORT_URL/report_$now/result.html"
      - printenv