version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get install -y sudo
      - sudo apt-get update -y
      - sudo apt-get install -y apt-transport-https
      - echo Installing source NPM dependencies...
      - sudo npm install forever -g
      - sudo npm install -g @angular/cli
      - sudo npm install
      - sudo node node_modules/node-sass/scripts/install.js
      - sudo npm rebuild node-sass
      - sudo printf '' > src/environments/environment.ts
  build:
    commands:
      - chmod +x ./env.sh
      - ./env.sh
      - echo Build started on `date`
      - sudo ng build --configuration=$BUILD_CONFIG
  post_build:
    commands:
      - aws s3 sync www/ s3://$S3_BUCKET/ --delete
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths '/*'
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - tsconfig.json
    - tslint.json
    - angular.json
    - ionic.config.json
    - src/**/*
    - www/**/*
    - node_modules/**/*
    - android/**/*
    - ios/**/*