version: '3'

services:
  cutie:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cutie
    ports:
      - "4202:4202"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
