################################################
#  GITHUB ACTION WORKFLOW NAME
################################################
name: Deploy to p1-au live environment


################################################
#  GITHUB ACTION EVENT TRIGGER
################################################
on: 
  workflow_dispatch:
    inputs:
      BRANCH_TAG_NAME:
        description: 'New tag version based on create-release-tag workflow'     
        required: true
        default: ''
      REQUESTOR:
        description: 'Requestor Name'     
        required: true
        default: ''
      REASON:
        description: 'Reason for deployment'     
        required: true
        default: ''
    

################################################
#  GITHUB ACTION JOBS
################################################
jobs:
  deploy-p1-au-live:
    name: deploy-p1-au-live
    runs-on: ubuntu-latest


################################################
#  GITHUB ACTIONS GLOBAL ENV VARIABLES  
################################################
    env:
      REGION : ap-southeast-2
      ENV : live # Valid values are dev,test,live only
      STACK_NAME: p1-au # Valid values are au,us,uk,p2,lf,nu,p1-sandbox,p1-stage,p2-sandbox,shared only
      ROOTSTACK: cutie-app
      CFNS3BucketName: devops-cfn-templates
      PRIVATES3BucketName: devops-shared-private
      PUBLICZONENAME: au.practera.com
      BUILD_CONFIG: custom
      STATUSREPORTS3Bucket: deployment-status.practera.com
      STATUS: DEPLOYED
      REQUESTOR: ${{ github.event.inputs.REQUESTOR }}
      REASON: ${{ github.event.inputs.REASON }}
      ENDPOINT: https://cutie.api.practera.com
      BRANCH_TAG_NAME: ${{ github.event.inputs.BRANCH_TAG_NAME }}
      CUTIEAPPS3: new-admin-live
      CUTIEAPPCDN: E3OEURB5XY00QG
      



################################################
#  GITHUB REPO CHECKOUT 
################################################
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          ref: ${{ github.event.inputs.BRANCH_TAG_NAME }}


################################################
#  NODE ENV
################################################    
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      

################################################
#  NODE MODULES CACHE  
################################################
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-


################################################
#  NODE MODULES INSTALL  
################################################
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run:  npm install


################################################
#  AWS CLI CONFIGURATION - DEVOPS 
################################################ 
      - name: Configure AWS credentials from $STACK_NAME account in $REGION region
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEVOPS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEVOPS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2


##########################################################
#  AWS DEPLOY SECRET - MASK CONSOLE DISPLAY
##########################################################
      - name: AWS Deploy Secret
        id: DeploySecret
        run: |
          echo "Enable SLACK NOTIFY"
          SLACK_WEBHOOK_URL=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-DEPLOY-$ENV| jq --raw-output '.SecretString' | jq -r .SLACK_WEBHOOK_URL)
          echo "::add-mask::$SLACK_WEBHOOK_URL"
          echo "::set-output name=SLACK_WEBHOOK_URL::$SLACK_WEBHOOK_URL"
    
          echo "Enable P1 AU ACCOUNT CLI Login"
          P1_PROD_AWS_ACCESS_KEY_ID=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-DEPLOY-$ENV| jq --raw-output '.SecretString' | jq -r .P1_PROD_AWS_ACCESS_KEY_ID)
          P1_PROD_AWS_SECRET_ACCESS_KEY=$(aws secretsmanager get-secret-value --secret-id $STACK_NAME-DEPLOY-$ENV| jq --raw-output '.SecretString' | jq -r .P1_PROD_AWS_SECRET_ACCESS_KEY)
          echo "::add-mask::$P1_PROD_AWS_ACCESS_KEY_ID"
          echo "::add-mask::$P1_PROD_AWS_SECRET_ACCESS_KEY"
          echo "::set-output name=P1_PROD_AWS_ACCESS_KEY_ID::$P1_PROD_AWS_ACCESS_KEY_ID"
          echo "::set-output name=P1_PROD_AWS_SECRET_ACCESS_KEY::$P1_PROD_AWS_SECRET_ACCESS_KEY"
        
        env:  #TODO: Update once manually to new stack accordingly
          STACK_NAME: shared # Valid values are au,us,uk,p2,lf,nu,p1-sandbox,p1-stage,p2-sandbox,shared only
          ENV: live # Valid values are sandbox,stage,live only


##########################################################
#  AWS P1 AU ACCOUNT STEPS BELOW
##########################################################
      - name: Configure AWS credentials from $STACK_NAME account in $REGION region
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.DeploySecret.outputs.P1_PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ steps.DeploySecret.outputs.P1_PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}}
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.DeploySecret.outputs.P1_PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.DeploySecret.outputs.P1_PROD_AWS_SECRET_ACCESS_KEY }}
   

          
###############################################################
#  ANGULAR ENVIRONMENT CREATION
##############################################################
      - name: Angular Environment creation
        run: |
          printf "Creating required secret variables for angular environment variable creation\n\n"

          export CUSTOM_APPKEY=$(aws secretsmanager get-secret-value --secret-id live/api/appkey | jq --raw-output '.SecretString' | jq -r .appkey)
          export CUSTOM_FILESTACK_SIGNATURE=$(aws secretsmanager get-secret-value --secret-id live/api/filestack | jq --raw-output '.SecretString' | jq -r .signature)
          export CUSTOM_FILESTACK_VIRUS_DETECTION=$(aws secretsmanager get-secret-value --secret-id live/api/filestack | jq --raw-output '.SecretString' | jq -r .virusdetection)
          export CUSTOM_FILESTACK_KEY=$(aws secretsmanager get-secret-value --secret-id live/api/filestack | jq --raw-output '.SecretString' | jq -r .apikey)
          export CUSTOM_FILESTACK_POLICY=$(aws secretsmanager get-secret-value --secret-id live/api/filestack | jq --raw-output '.SecretString' | jq -r .policy)
          export CUSTOM_PUSHERKEY=$(aws secretsmanager get-secret-value --secret-id live/api/pusher | jq --raw-output '.SecretString' | jq -r .key)
         
          printf "Angular environment variable creation  complete\n\n"
          printf "Executing env.sh script\n\n"
          chmod +x env.sh && ./env.sh
        env:
          CUSTOM_APPENV: live
          CUSTOM_AWS_REGION_CHINA: ap-northeast-2
          CUSTOM_S3_BUCKET_CHINA: practera-seoul-1
          CUSTOM_CHATGEAPHQLENDPOINT: https://chat-api.au.practera.com/graphql
          CUSTOM_PATH_IMAGE: /appv2/live/uploads/
          CUSTOM_AWS_REGION: ap-southeast-2
          CUSTOM_PATH_ANY: /appv2/live/uploads/
          CUSTOM_S3_BUCKET: practera-aus
          CUSTOM_APIENDPOINT: https://cutie.api.practera.com/
          CUSTOM_APIENDPOINTOLD: https://api.practera.com/
          CUSTOM_PRACTERCORE: https://my.practera.com
          CUSTOM_PATH_VIDEO: /media/fpvideo/upload/
          CUSTOM_GEAPHQLENDPOINT: https://core-graphql-api.au.practera.com/
          

 
###############################################################
#  BUILD WEB PACKAGES
##############################################################
      - name: Build Web Packages
        run: |
          printf '' > src/environments/environment.ts
          node_modules/.bin/ng build --configuration=${{ env.BUILD_CONFIG }}


##########################################################
#  AWS S3 SYNC OPERATIONS
##########################################################
      - name: AWS S3 Sync Operations
        run: |
          # CUTIEAPPS3=$(aws cloudformation list-exports --query "Exports[?Name==\`$STACK_NAME-CUTIES3BUCKET-$ENV\`].Value" --no-paginate --output text)
          aws s3 sync www/ s3://$CUTIEAPPS3 --delete



##########################################################
#  AWS CDN CACHE INVALIDATION
##########################################################
      - name: AWS Cloudfront Cache invalidation
        run: |
          # CUTIEAPPCDN=$(aws cloudformation list-exports --query "Exports[?Name==\`$STACK_NAME-CutieCloudFrontDistributionID-$ENV\`].Value" --no-paginate --output text)
          for i in $CUTIEAPPCDN;do aws cloudfront create-invalidation --distribution-id $i --paths "/*";done



##########################################################
#  SLACK NOTIFICATION
##########################################################  
      - name: Slack Notification
        if: always() # Pick up events even if the job fails or is canceled.
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
        with:
          status: ${{ job.status }}
          author_name: ${{ env.BRANCH_TAG_NAME }} -  ${{ env.ROOTSTACK }} deployed to ${{ env.ENV }} environemnt in ${{ env.STACK_NAME }} AWS account
          mention: 'here'
          if_mention: failure,cancelled
          job_name: deploy-p1-au-live # Match the name above.
          fields: repo,commit,eventName,ref,workflow,message,author,job,took
          custom_payload: |
            {
            username: 'GitHub Action CI WorkFlow',
            icon_emoji: ':github:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : ${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text:
             `${process.env.AS_REPO}\n
              ${process.env.AS_COMMIT}\n
              ${process.env.AS_EVENT_NAME}\n
              @${process.env.AS_REF}\n
              @${process.env.AS_WORKFLOW}\n
              ${process.env.AS_MESSAGE}\n
              ${process.env.AS_AUTHOR}\n
              ${process.env.AS_JOB}\n
              ${process.env.AS_TOOK}`,
            }]
            }


# ################################################
# #  STATUS VARIABLE UPDATE
# ################################################ 
      - name: Deployment status variable update
        if: ${{ failure() }}
        run: |
          echo "STATUS=FAILURE" >> $GITHUB_ENV

# ################################################
# #  DEVOPS-DEPLOYMENT REPORT
# ################################################ 
      - name: DevOps Deployment Reporting
        if: always()
        run: |
          pip install --upgrade pip
          pip install --upgrade csvtotable
          aws s3 cp s3://$STATUSREPORTS3Bucket/deploy-reporting.sh deploy-reporting.sh
          chmod +x deploy-reporting.sh && ./deploy-reporting.sh
          echo "LINK="${GITHUB_REPOSITORY##*/}.html >> $GITHUB_ENV